### ISSUE TITLE
SAS arşivlenirken açıklamaya link eklensin

### ISSUE THREAD

**Issue by Mavrikant** [Turkce-Vikipedi-Yazilim-Deposu/Arsivleyici#2]
Twinkle SAS eklerken açıklamaya link ekliyor. BOT'ta kaldırırken link eklense güzel olur. 

https://tr.wikipedia.org/w/index.php?title=Vikipedi:Silinmeye_aday_sayfalar&action=history

**Comment by evolutionoftheuniverse** [comment]
#3

**Comment by Mavrikant** [comment]
@evrifaessa merge-deploy yapabilir misin?

**Comment by yagiz-dev** [comment]
deploy geliyor.
