### ISSUE TITLE
Arşivlemede fazla satır

### ISSUE THREAD

**Issue by Khutuck** [Turkce-Vikipedi-Yazilim-Deposu/Arsivleyici#4]
https://tr.wikipedia.org/w/index.php?title=Vikipedi:Kategori_tart%C4%B1%C5%9Fmalar%C4%B1&curid=1475389&diff=24061541&oldid=24055698

Örnekte olduğu gibi şablon çıkartılınca fazladan bir satır kalıyor. 

Kodda 101. satırda şu değişiklik iş görür sanırım:
- newContent = content.replace("{{Vikipedi:Silinmeye aday sayfalar/" + page + "}}", "")
+ newContent = content.replace("{{Vikipedi:Silinmeye aday sayfalar/" + page + "}}\n", "")

**Comment by yagiz-dev** [comment]
bunu SAS için düzeltmiştim. ama KT zaten 2 ayda bir talep gördüğü için gerek duymamıştım. izin verirseniz botun şu anki tek operatörü olarak değişikliği müsait bir zamanımda ben deploy edeyim..

**Comment by yagiz-dev** [comment]
Yapıldı.
